# $Id: Makefile,v 1.7 2008/08/19 21:54:00 cdidier Exp $

LIB= text_xmpp
SRCS=	text-core.c \
	text-composing.c

LIB_INCS = -I../../src/fe-text/include/irssi/src/fe-text
LIB_LIBS = `pkg-config --libs glib-2.0`

include ../rules.mk
