# $Id: Makefile,v 1.16 2008/08/15 00:25:21 cdidier Exp $

LIB= fe_xmpp
SRCS=	fe-xmpp-queries.c \
	fe-xmpp-status.c \
	fe-rosters.c \
	fe-stanzas.c \
	fe-xmpp-core.c \
	module-formats.c \
	xmpp-completion.c

LIB_LIBS = `pkg-config --libs glib-2.0`

include ../rules.mk
