# $Id: Makefile,v 1.17 2008/08/19 14:51:57 cdidier Exp $

LIB= fe_xmpp
SRCS=	fe-xmpp-messages.c \
	fe-xmpp-queries.c \
	fe-xmpp-status.c \
	fe-xmpp-windows.c \
	fe-rosters.c \
	fe-stanzas.c \
	fe-xmpp-core.c \
	module-formats.c \
	xmpp-completion.c

LIB_LIBS = `pkg-config --libs glib-2.0`

include ../rules.mk
